#!/usr/bin/env bash
# this script configures a HAproxy server
# to automatically direct http to https

frontend www-http
    bind *:80
    mode http
    default_backend web-backend
frontend www-https
    bind *:443 ssl crt /etc/haproxy/realflore.tech.pem
    http-request set-header X-Forwarded-Proto https
    acl letsencrypt-acl path_beg /.well-known/acme-challenge/
    use_backend letsencrypt-backend if letsencrypt-acl
    default_backend web-backend

backend web-backend
    redirect scheme https unless { ssl_fc }
    balance roundrobin
    server 5472-web-01 54.242.147.163:80 check
    server 5472-web-02 34.229.200.198:80 check
backend letsencrypt-backend
   server letsencrypt 127.0.0.1:54321
